auto_scale_lr = dict(base_batch_size=512)
backend_args = dict(backend='local')
base_lr = 0.004
codec = dict(
    input_size=(
        192,
        256,
    ),
    normalize=False,
    sigma=(
        4.9,
        5.66,
    ),
    simcc_split_ratio=2.0,
    type='SimCCLabel',
    use_dark=False)
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
    dict(
        switch_epoch=30,
        switch_pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(
                rotate_factor=60,
                scale_factor=[
                    0.75,
                    1.25,
                ],
                shift_factor=0.0,
                type='RandomBBoxTransform'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=0.5,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        192,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        4.9,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='mmdet.PipelineSwitchHook'),
]
data_mode = 'topdown'
data_root = 'custom_underwater_dataset'
dataset_info = dict(
    dataset_name='underwater_pose',
    flip_pairs=[],
    joint_weights=[
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
    ],
    keypoint_info=dict({
        0:
        dict(
            color=[
                255,
                0,
                0,
            ],
            id=0,
            name='finger_tip',
            swap='',
            type='upper'),
        1:
        dict(color=[
            255,
            85,
            0,
        ], id=1, name='wrist', swap='', type='upper'),
        2:
        dict(color=[
            255,
            170,
            0,
        ], id=2, name='elbow', swap='', type='upper'),
        3:
        dict(color=[
            255,
            255,
            0,
        ], id=3, name='head', swap='', type='upper'),
        4:
        dict(
            color=[
                170,
                255,
                0,
            ],
            id=4,
            name='shoulder',
            swap='',
            type='upper'),
        5:
        dict(color=[
            85,
            255,
            0,
        ], id=5, name='pelvis', swap='', type='lower'),
        6:
        dict(color=[
            0,
            255,
            0,
        ], id=6, name='hip', swap='', type='lower'),
        7:
        dict(color=[
            0,
            255,
            85,
        ], id=7, name='knee', swap='', type='lower'),
        8:
        dict(color=[
            0,
            255,
            170,
        ], id=8, name='ankle', swap='', type='lower'),
        9:
        dict(color=[
            0,
            255,
            255,
        ], id=9, name='toe', swap='', type='lower')
    }),
    num_keypoints=10,
    pose_kpt_color=[
        [
            255,
            0,
            0,
        ],
        [
            255,
            85,
            0,
        ],
        [
            255,
            170,
            0,
        ],
        [
            255,
            255,
            0,
        ],
        [
            170,
            255,
            0,
        ],
        [
            85,
            255,
            0,
        ],
        [
            0,
            255,
            0,
        ],
        [
            0,
            255,
            85,
        ],
        [
            0,
            255,
            170,
        ],
        [
            0,
            255,
            255,
        ],
    ],
    pose_link_color=[
        [
            255,
            0,
            0,
        ],
        [
            0,
            255,
            0,
        ],
        [
            0,
            0,
            255,
        ],
        [
            255,
            255,
            0,
        ],
        [
            255,
            0,
            255,
        ],
        [
            0,
            255,
            255,
        ],
        [
            255,
            85,
            0,
        ],
        [
            85,
            255,
            0,
        ],
        [
            0,
            170,
            255,
        ],
    ],
    sigmas=[
        0.2,
        0.25,
        0.3,
        0.25,
        0.3,
        0.35,
        0.35,
        0.3,
        0.25,
        0.2,
    ],
    skeleton=[
        [
            0,
            1,
        ],
        [
            1,
            2,
        ],
        [
            2,
            3,
        ],
        [
            3,
            4,
        ],
        [
            4,
            5,
        ],
        [
            5,
            6,
        ],
        [
            6,
            7,
        ],
        [
            7,
            8,
        ],
        [
            8,
            9,
        ],
    ],
    skeleton_info=dict({
        0:
        dict(color=[
            255,
            0,
            0,
        ], id=0, link=(
            'finger_tip',
            'wrist',
        )),
        1:
        dict(color=[
            0,
            255,
            0,
        ], id=1, link=(
            'wrist',
            'elbow',
        )),
        2:
        dict(color=[
            0,
            0,
            255,
        ], id=2, link=(
            'elbow',
            'head',
        )),
        3:
        dict(color=[
            255,
            255,
            0,
        ], id=3, link=(
            'head',
            'shoulder',
        )),
        4:
        dict(color=[
            255,
            0,
            255,
        ], id=4, link=(
            'shoulder',
            'pelvis',
        )),
        5:
        dict(color=[
            0,
            255,
            255,
        ], id=5, link=(
            'pelvis',
            'hip',
        )),
        6:
        dict(color=[
            255,
            85,
            0,
        ], id=6, link=(
            'hip',
            'knee',
        )),
        7:
        dict(color=[
            85,
            255,
            0,
        ], id=7, link=(
            'knee',
            'ankle',
        )),
        8:
        dict(color=[
            0,
            170,
            255,
        ], id=8, link=(
            'ankle',
            'toe',
        ))
    }))
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        max_keep_ckpts=1,
        rule='greater',
        save_best='coco/AP',
        type='CheckpointHook'))
default_scope = 'mmpose'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
load_from = None
log_level = 'INFO'
log_processor = dict(
    by_epoch=True, num_digits=6, type='LogProcessor', window_size=50)
max_epochs = 60
model = dict(
    backbone=dict(
        _scope_='mmdet',
        act_cfg=dict(type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=1.0,
        expand_ratio=0.5,
        init_cfg=None,
        norm_cfg=dict(type='SyncBN'),
        out_indices=(4, ),
        type='CSPNeXt',
        widen_factor=1.0),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='PoseDataPreprocessor'),
    head=dict(
        decoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        final_layer_kernel_size=7,
        gau_cfg=dict(
            act_fn='SiLU',
            drop_path=0.0,
            dropout_rate=0.0,
            expansion_factor=2,
            hidden_dims=256,
            pos_enc=False,
            s=128,
            use_rel_bias=False),
        in_channels=1024,
        in_featuremap_size=(
            6,
            8,
        ),
        input_size=(
            192,
            256,
        ),
        loss=dict(
            beta=10.0,
            label_softmax=True,
            type='KLDiscretLoss',
            use_target_weight=True),
        out_channels=10,
        simcc_split_ratio=2.0,
        type='RTMCCHead'),
    test_cfg=dict(flip_test=False),
    type='TopdownPoseEstimator')
optim_wrapper = dict(
    optimizer=dict(lr=0.004, type='AdamW', weight_decay=0.05),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=1e-05,
        type='LinearLR'),
    dict(
        T_max=30,
        begin=30,
        by_epoch=True,
        convert_to_iter_based=True,
        end=60,
        eta_min=0.0002,
        type='CosineAnnealingLR'),
]
randomness = dict(seed=21)
resume = False
stage2_num_epochs = 30
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/test.json',
        data_mode='topdown',
        data_prefix=dict(img='images/test/'),
        data_root='custom_underwater_dataset',
        metainfo=dict(
            dataset_name='underwater_pose',
            flip_pairs=[],
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='finger_tip',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        255,
                        85,
                        0,
                    ],
                    id=1,
                    name='wrist',
                    swap='',
                    type='upper'),
                2:
                dict(
                    color=[
                        255,
                        170,
                        0,
                    ],
                    id=2,
                    name='elbow',
                    swap='',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='head',
                    swap='',
                    type='upper'),
                4:
                dict(
                    color=[
                        170,
                        255,
                        0,
                    ],
                    id=4,
                    name='shoulder',
                    swap='',
                    type='upper'),
                5:
                dict(
                    color=[
                        85,
                        255,
                        0,
                    ],
                    id=5,
                    name='pelvis',
                    swap='',
                    type='lower'),
                6:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=6,
                    name='hip',
                    swap='',
                    type='lower'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        85,
                    ],
                    id=7,
                    name='knee',
                    swap='',
                    type='lower'),
                8:
                dict(
                    color=[
                        0,
                        255,
                        170,
                    ],
                    id=8,
                    name='ankle',
                    swap='',
                    type='lower'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=9,
                    name='toe',
                    swap='',
                    type='lower')
            }),
            num_keypoints=10,
            pose_kpt_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    255,
                    170,
                    0,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    170,
                    255,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    85,
                ],
                [
                    0,
                    255,
                    170,
                ],
                [
                    0,
                    255,
                    255,
                ],
            ],
            pose_link_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    0,
                    255,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    255,
                    0,
                    255,
                ],
                [
                    0,
                    255,
                    255,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    170,
                    255,
                ],
            ],
            sigmas=[
                0.2,
                0.25,
                0.3,
                0.25,
                0.3,
                0.35,
                0.35,
                0.3,
                0.25,
                0.2,
            ],
            skeleton=[
                [
                    0,
                    1,
                ],
                [
                    1,
                    2,
                ],
                [
                    2,
                    3,
                ],
                [
                    3,
                    4,
                ],
                [
                    4,
                    5,
                ],
                [
                    5,
                    6,
                ],
                [
                    6,
                    7,
                ],
                [
                    7,
                    8,
                ],
                [
                    8,
                    9,
                ],
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ], id=0, link=(
                        'finger_tip',
                        'wrist',
                    )),
                1:
                dict(color=[
                    0,
                    255,
                    0,
                ], id=1, link=(
                    'wrist',
                    'elbow',
                )),
                2:
                dict(color=[
                    0,
                    0,
                    255,
                ], id=2, link=(
                    'elbow',
                    'head',
                )),
                3:
                dict(color=[
                    255,
                    255,
                    0,
                ], id=3, link=(
                    'head',
                    'shoulder',
                )),
                4:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ], id=4, link=(
                        'shoulder',
                        'pelvis',
                    )),
                5:
                dict(color=[
                    0,
                    255,
                    255,
                ], id=5, link=(
                    'pelvis',
                    'hip',
                )),
                6:
                dict(color=[
                    255,
                    85,
                    0,
                ], id=6, link=(
                    'hip',
                    'knee',
                )),
                7:
                dict(color=[
                    85,
                    255,
                    0,
                ], id=7, link=(
                    'knee',
                    'ankle',
                )),
                8:
                dict(color=[
                    0,
                    170,
                    255,
                ], id=8, link=(
                    'ankle',
                    'toe',
                ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='custom_underwater_dataset/annotations/test.json',
    type='CocoMetric')
train_cfg = dict(max_epochs=60, val_interval=10)
train_dataloader = dict(
    batch_size=32,
    dataset=dict(
        ann_file='annotations/train.json',
        data_mode='topdown',
        data_prefix=dict(img='images/train/'),
        data_root='custom_underwater_dataset',
        metainfo=dict(
            dataset_name='underwater_pose',
            flip_pairs=[],
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='finger_tip',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        255,
                        85,
                        0,
                    ],
                    id=1,
                    name='wrist',
                    swap='',
                    type='upper'),
                2:
                dict(
                    color=[
                        255,
                        170,
                        0,
                    ],
                    id=2,
                    name='elbow',
                    swap='',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='head',
                    swap='',
                    type='upper'),
                4:
                dict(
                    color=[
                        170,
                        255,
                        0,
                    ],
                    id=4,
                    name='shoulder',
                    swap='',
                    type='upper'),
                5:
                dict(
                    color=[
                        85,
                        255,
                        0,
                    ],
                    id=5,
                    name='pelvis',
                    swap='',
                    type='lower'),
                6:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=6,
                    name='hip',
                    swap='',
                    type='lower'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        85,
                    ],
                    id=7,
                    name='knee',
                    swap='',
                    type='lower'),
                8:
                dict(
                    color=[
                        0,
                        255,
                        170,
                    ],
                    id=8,
                    name='ankle',
                    swap='',
                    type='lower'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=9,
                    name='toe',
                    swap='',
                    type='lower')
            }),
            num_keypoints=10,
            pose_kpt_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    255,
                    170,
                    0,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    170,
                    255,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    85,
                ],
                [
                    0,
                    255,
                    170,
                ],
                [
                    0,
                    255,
                    255,
                ],
            ],
            pose_link_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    0,
                    255,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    255,
                    0,
                    255,
                ],
                [
                    0,
                    255,
                    255,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    170,
                    255,
                ],
            ],
            sigmas=[
                0.2,
                0.25,
                0.3,
                0.25,
                0.3,
                0.35,
                0.35,
                0.3,
                0.25,
                0.2,
            ],
            skeleton=[
                [
                    0,
                    1,
                ],
                [
                    1,
                    2,
                ],
                [
                    2,
                    3,
                ],
                [
                    3,
                    4,
                ],
                [
                    4,
                    5,
                ],
                [
                    5,
                    6,
                ],
                [
                    6,
                    7,
                ],
                [
                    7,
                    8,
                ],
                [
                    8,
                    9,
                ],
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ], id=0, link=(
                        'finger_tip',
                        'wrist',
                    )),
                1:
                dict(color=[
                    0,
                    255,
                    0,
                ], id=1, link=(
                    'wrist',
                    'elbow',
                )),
                2:
                dict(color=[
                    0,
                    0,
                    255,
                ], id=2, link=(
                    'elbow',
                    'head',
                )),
                3:
                dict(color=[
                    255,
                    255,
                    0,
                ], id=3, link=(
                    'head',
                    'shoulder',
                )),
                4:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ], id=4, link=(
                        'shoulder',
                        'pelvis',
                    )),
                5:
                dict(color=[
                    0,
                    255,
                    255,
                ], id=5, link=(
                    'pelvis',
                    'hip',
                )),
                6:
                dict(color=[
                    255,
                    85,
                    0,
                ], id=6, link=(
                    'hip',
                    'knee',
                )),
                7:
                dict(color=[
                    85,
                    255,
                    0,
                ], id=7, link=(
                    'knee',
                    'ankle',
                )),
                8:
                dict(color=[
                    0,
                    170,
                    255,
                ], id=8, link=(
                    'ankle',
                    'toe',
                ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(
                rotate_factor=80,
                scale_factor=[
                    0.6,
                    1.4,
                ],
                type='RandomBBoxTransform'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=1.0,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        192,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        4.9,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='CocoDataset'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(
        rotate_factor=80,
        scale_factor=[
            0.6,
            1.4,
        ],
        type='RandomBBoxTransform'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=1.0,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
train_pipeline_stage2 = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(
        rotate_factor=60,
        scale_factor=[
            0.75,
            1.25,
        ],
        shift_factor=0.0,
        type='RandomBBoxTransform'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=0.5,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=32,
    dataset=dict(
        ann_file='annotations/val.json',
        data_mode='topdown',
        data_prefix=dict(img='images/val/'),
        data_root='custom_underwater_dataset',
        metainfo=dict(
            dataset_name='underwater_pose',
            flip_pairs=[],
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='finger_tip',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        255,
                        85,
                        0,
                    ],
                    id=1,
                    name='wrist',
                    swap='',
                    type='upper'),
                2:
                dict(
                    color=[
                        255,
                        170,
                        0,
                    ],
                    id=2,
                    name='elbow',
                    swap='',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='head',
                    swap='',
                    type='upper'),
                4:
                dict(
                    color=[
                        170,
                        255,
                        0,
                    ],
                    id=4,
                    name='shoulder',
                    swap='',
                    type='upper'),
                5:
                dict(
                    color=[
                        85,
                        255,
                        0,
                    ],
                    id=5,
                    name='pelvis',
                    swap='',
                    type='lower'),
                6:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=6,
                    name='hip',
                    swap='',
                    type='lower'),
                7:
                dict(
                    color=[
                        0,
                        255,
                        85,
                    ],
                    id=7,
                    name='knee',
                    swap='',
                    type='lower'),
                8:
                dict(
                    color=[
                        0,
                        255,
                        170,
                    ],
                    id=8,
                    name='ankle',
                    swap='',
                    type='lower'),
                9:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=9,
                    name='toe',
                    swap='',
                    type='lower')
            }),
            num_keypoints=10,
            pose_kpt_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    255,
                    170,
                    0,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    170,
                    255,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    255,
                    85,
                ],
                [
                    0,
                    255,
                    170,
                ],
                [
                    0,
                    255,
                    255,
                ],
            ],
            pose_link_color=[
                [
                    255,
                    0,
                    0,
                ],
                [
                    0,
                    255,
                    0,
                ],
                [
                    0,
                    0,
                    255,
                ],
                [
                    255,
                    255,
                    0,
                ],
                [
                    255,
                    0,
                    255,
                ],
                [
                    0,
                    255,
                    255,
                ],
                [
                    255,
                    85,
                    0,
                ],
                [
                    85,
                    255,
                    0,
                ],
                [
                    0,
                    170,
                    255,
                ],
            ],
            sigmas=[
                0.2,
                0.25,
                0.3,
                0.25,
                0.3,
                0.35,
                0.35,
                0.3,
                0.25,
                0.2,
            ],
            skeleton=[
                [
                    0,
                    1,
                ],
                [
                    1,
                    2,
                ],
                [
                    2,
                    3,
                ],
                [
                    3,
                    4,
                ],
                [
                    4,
                    5,
                ],
                [
                    5,
                    6,
                ],
                [
                    6,
                    7,
                ],
                [
                    7,
                    8,
                ],
                [
                    8,
                    9,
                ],
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ], id=0, link=(
                        'finger_tip',
                        'wrist',
                    )),
                1:
                dict(color=[
                    0,
                    255,
                    0,
                ], id=1, link=(
                    'wrist',
                    'elbow',
                )),
                2:
                dict(color=[
                    0,
                    0,
                    255,
                ], id=2, link=(
                    'elbow',
                    'head',
                )),
                3:
                dict(color=[
                    255,
                    255,
                    0,
                ], id=3, link=(
                    'head',
                    'shoulder',
                )),
                4:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ], id=4, link=(
                        'shoulder',
                        'pelvis',
                    )),
                5:
                dict(color=[
                    0,
                    255,
                    255,
                ], id=5, link=(
                    'pelvis',
                    'hip',
                )),
                6:
                dict(color=[
                    255,
                    85,
                    0,
                ], id=6, link=(
                    'hip',
                    'knee',
                )),
                7:
                dict(color=[
                    85,
                    255,
                    0,
                ], id=7, link=(
                    'knee',
                    'ankle',
                )),
                8:
                dict(color=[
                    0,
                    170,
                    255,
                ], id=8, link=(
                    'ankle',
                    'toe',
                ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='custom_underwater_dataset/annotations/val.json',
    type='CocoMetric')
val_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='PackPoseInputs'),
]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
